name: Build Android APK (ZIP)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: Install unzip and Gradle
        run: sudo apt-get update && sudo apt-get install -y unzip gradle

      - name: Unzip project
        run: unzip eden_ac_android_project_ci.zip -d .

      - name: Generate Gradle wrapper
        run: gradle wrapper --gradle-version 8.7

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: eden-ac-apk
          path: app/build/outputs/apk/debug/app-debug.apk
